name: Code Analysis

on: [push, pull_request]

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Code Analysis
        run: python analyze.py
